### ISSUE TITLE
ade tree fails when collection contains a git repo as dependency

### ISSUE THREAD

**Issue by lask79** [ansible/ansible-dev-environment#118] opened 2024-02-25 16:26 UTC
**Issue**

When I try to install my current collection that has a dependency to a git repository using:

ade install -e . --venv .venv

galaxy.yml
```
dependencies: {'git@github.com:organization/repo_name.git': 'devel'}
```

**I get this error:**
```
Traceback (most recent call last):
  File ".venv/bin/ade", line 8, in <module>
    sys.exit(main())/
  File ".venv/lib64/python3.10/site-packages/ansible_dev_environment/cli.py", line 177, in main
    cli.run()
  File ".venv/lib64/python3.10/site-packages/ansible_dev_environment/cli.py", line 158, in run
    subcommand.run()
  File ".venv/lib64/python3.10/site-packages/ansible_dev_environment/subcommands/treemaker.py", line 70, in run
    target[dep] = tree_dict[dep]
KeyError: 'git@github.com:organization/repo_name.git'
```

**Analyzation**
It looks ADE cannot use the git repo path as key. Is it possible to collect the real collection name out of the installed collection? the repo name is mostly not the same as the collection name.

**Comment by audgirka** [comment] 2024-04-24 13:24
Duplicate of #117

**Closed by audgirka** 2024-04-24 13:24 UTC
Labels: bug, new
